---

# TODO Ansible >= 2.3.0 works out of the box with python3, no need for this then
- hosts: all
  gather_facts: False
  become: yes
  become_user: root
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - setup: # aka gather_facts

- name: Install required packages
  hosts: all
  become: yes
  become_user: root
  vars_files:
    - vars/base.yml
  roles:
    - base